[package]
name = "ecdsa_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { path = "/zk-repos/halo2/halo2_proofs" }
rand = "0.8"
ff = "0.13"
group = "0.13"
pasta_curves = "0.5"
subtle = "2.4"